[package]
name = "outbe-emissionlimit"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
outbe-primitives.workspace = true
outbe-metadosis.workspace = true
alloy-primitives.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
