// @generated by `cargo xtask ocomp shape`.
// Measurement-only compile ceilings: never an armable network binding.

pub const OCOMP_SHAPE_SCHEMA_VERSION: u16 = 1;
pub const OCOMP_SHAPE_MEASUREMENT_ONLY: bool = true;
pub const OCOMP_SHAPE_ARMABLE: bool = false;
pub const OCOMP_POC_FORK_ID_HEX: &str =
    "1d1378c5bf42070e0326f13d3094f4b7ed3ef42c63edb3179745045f65027eb2";
pub const OCOMP_CORRECTNESS_PROFILE_ID_HEX: &str =
    "0469002bbc5065d8e9d200daede2a65ec479cad78210d7dadabdd5320d241c8d";
pub const OCOMP_CAPACITY_PROFILE_ID_HEX: &str =
    "7c9614691067b57829fba66f37e02860529ab1a24497dbb8f5b53dc5bd0f52df";
pub const OCOMP_SHAPE_GENERATOR_SOURCE_SHA256: &str =
    "03d1fb4ec66fd75c07e858ea42b623b244417c9d2a3ce5f3a075f840ae818360";
pub const OCOMP_SHAPE_INPUT_SET_SHA256: &str =
    "b372126e8ff1eae8816b803fae03163d9f775cd2629bc92db45b93720f8247ed";
pub const OCOMP_CANDIDATE_LIMITS_SHA256: &str =
    "a3c6ad4cf52140a9ebfc48eef7aafb8af80af59104f0070d09959cd042b13150";
pub const OCOMP_MINIMUM_MACHINE_SHA256: &str =
    "a54ca8d53824f9dcf439267cbd93a939d3f09823703d1678540acb9a588720b7";
pub const OCOMP_HEADROOM_POLICY_SHA256: &str =
    "3a44462d5a5a61bb9065dce7549f727b160757ec50ac574ebe69121feeaa0aaf";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OcompPocCandidateLimitsV1 {
    pub max_tributes_per_work_shard: u64,
    pub max_inputs_per_work_unit: u64,
    pub max_result_chunk_bytes: u64,
    pub max_result_summary_bytes: u64,
    pub max_activation_payload_bytes: u64,
    pub max_finalized_intent_proof_bytes: u64,
    pub max_result_vote_bytes: u64,
    pub max_activation_ocb1_bytes: u64,
    pub max_activation_calldata_bytes: u64,
    pub max_transaction_rlp_bytes: u64,
    pub max_receipt_bytes: u64,
    pub max_log_count: u64,
    pub max_log_bytes: u64,
    pub max_input_manifest_bytes: u64,
    pub max_input_chunk_bytes: u64,
    pub max_records_per_input_chunk: u64,
    pub max_fidelity_openings_per_work_shard: u64,
    pub max_oracle_openings: u64,
    pub max_oracle_wwd_pair_entries: u64,
    pub max_active_scurve_entries: u64,
    pub max_opening_bytes: u64,
    pub max_nod_actions_per_result_chunk: u64,
    pub max_contributor_actions_per_result_chunk: u64,
    pub max_bucket_records_per_result_chunk: u64,
    pub max_protocol_collection_items: u64,
    pub max_activation_storage_reads: u64,
    pub max_activation_storage_writes: u64,
    pub max_activation_root_transitions: u64,
    pub max_signature_verifications: u64,
    pub activation_base_gas: u64,
    pub activation_per_input_byte_gas: u64,
    pub activation_per_root_transition_gas: u64,
    pub activation_per_opening_or_proof_byte_gas: u64,
    pub activation_per_signature_gas: u64,
    pub max_activation_gas: u64,
    pub max_activation_internal_work: u64,
    pub source_retention_after_terminal_blocks: u64,
}

pub const OCOMP_POC_CANDIDATE_LIMITS_V1: OcompPocCandidateLimitsV1 = OcompPocCandidateLimitsV1 {
    max_tributes_per_work_shard: 256,
    max_inputs_per_work_unit: 13,
    max_result_chunk_bytes: 524288,
    max_result_summary_bytes: 1048576,
    max_activation_payload_bytes: 65536,
    max_finalized_intent_proof_bytes: 524288,
    max_result_vote_bytes: 2048,
    max_activation_ocb1_bytes: 2097152,
    max_activation_calldata_bytes: 2097216,
    max_transaction_rlp_bytes: 2097408,
    max_receipt_bytes: 65536,
    max_log_count: 8,
    max_log_bytes: 65536,
    max_input_manifest_bytes: 262144,
    max_input_chunk_bytes: 1048576,
    max_records_per_input_chunk: 768,
    max_fidelity_openings_per_work_shard: 256,
    max_oracle_openings: 256,
    max_oracle_wwd_pair_entries: 256,
    max_active_scurve_entries: 256,
    max_opening_bytes: 262144,
    max_nod_actions_per_result_chunk: 256,
    max_contributor_actions_per_result_chunk: 256,
    max_bucket_records_per_result_chunk: 256,
    max_protocol_collection_items: 4096,
    max_activation_storage_reads: 64,
    max_activation_storage_writes: 32,
    max_activation_root_transitions: 4,
    max_signature_verifications: 3,
    activation_base_gas: 100000,
    activation_per_input_byte_gas: 16,
    activation_per_root_transition_gas: 25000,
    activation_per_opening_or_proof_byte_gas: 16,
    activation_per_signature_gas: 50000,
    max_activation_gas: 30000000,
    max_activation_internal_work: 10000000,
    source_retention_after_terminal_blocks: 64,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OcompPocDevnetMachineV1 {
    pub architecture: &'static str,
    pub operating_system: &'static str,
    pub logical_cpu_count: u64,
    pub nominal_memory_bytes: u64,
    pub minimum_process_memory_bytes: u64,
    pub nominal_root_disk_bytes: u64,
    pub minimum_free_workspace_bytes: u64,
    pub minimum_block_iops: u64,
    pub minimum_block_throughput_bytes_per_second: u64,
    pub init_and_resource_manager: &'static str,
    pub enclave_mode: &'static str,
}

pub const OCOMP_POC_DEVNET_MACHINE_V1: OcompPocDevnetMachineV1 = OcompPocDevnetMachineV1 {
    architecture: "x86_64",
    operating_system: "Ubuntu 24.04",
    init_and_resource_manager: "systemd + unified cgroup v2",
    enclave_mode: "production enclave under gramine-direct; no SGX claim",
    logical_cpu_count: 4,
    nominal_memory_bytes: 17179869184,
    minimum_process_memory_bytes: 12884901888,
    nominal_root_disk_bytes: 139586437120,
    minimum_free_workspace_bytes: 107374182400,
    minimum_block_iops: 8000,
    minimum_block_throughput_bytes_per_second: 250000000,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OcompPocHeadroomPolicyV1 {
    pub benchmark_cold_runs: u64,
    pub required_headroom_basis_points: u64,
    pub failed_or_timeout_run_rejects_candidate: bool,
    pub retry_failed_run: bool,
}

pub const OCOMP_POC_HEADROOM_POLICY_V1: OcompPocHeadroomPolicyV1 = OcompPocHeadroomPolicyV1 {
    benchmark_cold_runs: 5,
    required_headroom_basis_points: 2000,
    failed_or_timeout_run_rejects_candidate: true,
    retry_failed_run: false,
};
