// @generated by cargo xtask ocomp registry from registry/ocomp-v1.tsv.
// Do not edit by hand.

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum ObjectKind {
    ProtocolBundleV1 = 0x0001,
    CorrectnessProfileV1 = 0x0002,
    CapacityProfileV1 = 0x0003,
    PreAdmissionEnvelopeV1 = 0x0004,
    ActivationPreconditionsV1 = 0x0005,
    JobIntentV1 = 0x0006,
    FinalizedIntentProofV1 = 0x0007,
    InputManifestV1 = 0x0008,
    AuthenticatedInputChunkV1 = 0x0009,
    UnitSpecV1 = 0x000a,
    UnitArtifactV1 = 0x000b,
    ResultChunkV1 = 0x000c,
    LysisResultV1 = 0x000d,
    ActivationPayloadV1 = 0x000e,
    OcompKeyRegistrationV1 = 0x0010,
    ActiveGenerationV1 = 0x0013,
    AggregateActivationReceiptV1 = 0x0014,
    NodBatchReceiptV1 = 0x0015,
    ContributorReceiptV1 = 0x0016,
    TributeReceiptV1 = 0x0017,
    RequestBudgetSplitReceiptV1 = 0x0018,
    CarryOverReceiptV1 = 0x0019,
    SignOnceRecordV1 = 0x001b,
    ActivationCallCoreV1 = 0x001c,
    LysisArithmeticSummaryV1 = 0x001d,
    OcompJobRecordV1 = 0x001e,
    ShuffleRunArtifactV1 = 0x001f,
    ResultVoteV1 = 0x0020,
    EquivocationEvidenceV1 = 0x0021,
    ResultVoteSlotV1 = 0x0022,
    OcompQuorumV1 = 0x0023,
    OcompAccountabilitySummaryV1 = 0x0024,
    OcompVoteAccountabilityV1 = 0x0025,
    LysisTerminalV1 = 0x0026,
    NodMaterializationBatchV1 = 0x0027,
    NodMaterializationHeadV1 = 0x0028,
}

impl ObjectKind {
    pub const ALL: &'static [Self] = &[
        Self::ProtocolBundleV1,
        Self::CorrectnessProfileV1,
        Self::CapacityProfileV1,
        Self::PreAdmissionEnvelopeV1,
        Self::ActivationPreconditionsV1,
        Self::JobIntentV1,
        Self::FinalizedIntentProofV1,
        Self::InputManifestV1,
        Self::AuthenticatedInputChunkV1,
        Self::UnitSpecV1,
        Self::UnitArtifactV1,
        Self::ResultChunkV1,
        Self::LysisResultV1,
        Self::ActivationPayloadV1,
        Self::OcompKeyRegistrationV1,
        Self::ActiveGenerationV1,
        Self::AggregateActivationReceiptV1,
        Self::NodBatchReceiptV1,
        Self::ContributorReceiptV1,
        Self::TributeReceiptV1,
        Self::RequestBudgetSplitReceiptV1,
        Self::CarryOverReceiptV1,
        Self::SignOnceRecordV1,
        Self::ActivationCallCoreV1,
        Self::LysisArithmeticSummaryV1,
        Self::OcompJobRecordV1,
        Self::ShuffleRunArtifactV1,
        Self::ResultVoteV1,
        Self::EquivocationEvidenceV1,
        Self::ResultVoteSlotV1,
        Self::OcompQuorumV1,
        Self::OcompAccountabilitySummaryV1,
        Self::OcompVoteAccountabilityV1,
        Self::LysisTerminalV1,
        Self::NodMaterializationBatchV1,
        Self::NodMaterializationHeadV1,
    ];

    #[must_use]
    pub const fn tag(self) -> u16 {
        self as u16
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::ProtocolBundleV1 => "ProtocolBundleV1",
            Self::CorrectnessProfileV1 => "CorrectnessProfileV1",
            Self::CapacityProfileV1 => "CapacityProfileV1",
            Self::PreAdmissionEnvelopeV1 => "PreAdmissionEnvelopeV1",
            Self::ActivationPreconditionsV1 => "ActivationPreconditionsV1",
            Self::JobIntentV1 => "JobIntentV1",
            Self::FinalizedIntentProofV1 => "FinalizedIntentProofV1",
            Self::InputManifestV1 => "InputManifestV1",
            Self::AuthenticatedInputChunkV1 => "AuthenticatedInputChunkV1",
            Self::UnitSpecV1 => "UnitSpecV1",
            Self::UnitArtifactV1 => "UnitArtifactV1",
            Self::ResultChunkV1 => "ResultChunkV1",
            Self::LysisResultV1 => "LysisResultV1",
            Self::ActivationPayloadV1 => "ActivationPayloadV1",
            Self::OcompKeyRegistrationV1 => "OcompKeyRegistrationV1",
            Self::ActiveGenerationV1 => "ActiveGenerationV1",
            Self::AggregateActivationReceiptV1 => "AggregateActivationReceiptV1",
            Self::NodBatchReceiptV1 => "NodBatchReceiptV1",
            Self::ContributorReceiptV1 => "ContributorReceiptV1",
            Self::TributeReceiptV1 => "TributeReceiptV1",
            Self::RequestBudgetSplitReceiptV1 => "RequestBudgetSplitReceiptV1",
            Self::CarryOverReceiptV1 => "CarryOverReceiptV1",
            Self::SignOnceRecordV1 => "SignOnceRecordV1",
            Self::ActivationCallCoreV1 => "ActivationCallCoreV1",
            Self::LysisArithmeticSummaryV1 => "LysisArithmeticSummaryV1",
            Self::OcompJobRecordV1 => "OcompJobRecordV1",
            Self::ShuffleRunArtifactV1 => "ShuffleRunArtifactV1",
            Self::ResultVoteV1 => "ResultVoteV1",
            Self::EquivocationEvidenceV1 => "EquivocationEvidenceV1",
            Self::ResultVoteSlotV1 => "ResultVoteSlotV1",
            Self::OcompQuorumV1 => "OcompQuorumV1",
            Self::OcompAccountabilitySummaryV1 => "OcompAccountabilitySummaryV1",
            Self::OcompVoteAccountabilityV1 => "OcompVoteAccountabilityV1",
            Self::LysisTerminalV1 => "LysisTerminalV1",
            Self::NodMaterializationBatchV1 => "NodMaterializationBatchV1",
            Self::NodMaterializationHeadV1 => "NodMaterializationHeadV1",
        }
    }
}

impl TryFrom<u16> for ObjectKind {
    type Error = crate::error::ProtocolError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0x0001 => Ok(Self::ProtocolBundleV1),
            0x0002 => Ok(Self::CorrectnessProfileV1),
            0x0003 => Ok(Self::CapacityProfileV1),
            0x0004 => Ok(Self::PreAdmissionEnvelopeV1),
            0x0005 => Ok(Self::ActivationPreconditionsV1),
            0x0006 => Ok(Self::JobIntentV1),
            0x0007 => Ok(Self::FinalizedIntentProofV1),
            0x0008 => Ok(Self::InputManifestV1),
            0x0009 => Ok(Self::AuthenticatedInputChunkV1),
            0x000a => Ok(Self::UnitSpecV1),
            0x000b => Ok(Self::UnitArtifactV1),
            0x000c => Ok(Self::ResultChunkV1),
            0x000d => Ok(Self::LysisResultV1),
            0x000e => Ok(Self::ActivationPayloadV1),
            0x0010 => Ok(Self::OcompKeyRegistrationV1),
            0x0013 => Ok(Self::ActiveGenerationV1),
            0x0014 => Ok(Self::AggregateActivationReceiptV1),
            0x0015 => Ok(Self::NodBatchReceiptV1),
            0x0016 => Ok(Self::ContributorReceiptV1),
            0x0017 => Ok(Self::TributeReceiptV1),
            0x0018 => Ok(Self::RequestBudgetSplitReceiptV1),
            0x0019 => Ok(Self::CarryOverReceiptV1),
            0x001b => Ok(Self::SignOnceRecordV1),
            0x001c => Ok(Self::ActivationCallCoreV1),
            0x001d => Ok(Self::LysisArithmeticSummaryV1),
            0x001e => Ok(Self::OcompJobRecordV1),
            0x001f => Ok(Self::ShuffleRunArtifactV1),
            0x0020 => Ok(Self::ResultVoteV1),
            0x0021 => Ok(Self::EquivocationEvidenceV1),
            0x0022 => Ok(Self::ResultVoteSlotV1),
            0x0023 => Ok(Self::OcompQuorumV1),
            0x0024 => Ok(Self::OcompAccountabilitySummaryV1),
            0x0025 => Ok(Self::OcompVoteAccountabilityV1),
            0x0026 => Ok(Self::LysisTerminalV1),
            0x0027 => Ok(Self::NodMaterializationBatchV1),
            0x0028 => Ok(Self::NodMaterializationHeadV1),
            value => Err(crate::error::ProtocolError::UnknownObjectKind(value)),
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum HashDomain {
    ProtocolBundle,
    PreAdmission,
    ActivationPreconditions,
    Intent,
    IntentSlot,
    Job,
    InputLease,
    InputChunk,
    InputManifest,
    CodecDescriptor,
    OpeningCodecRegistry,
    Plan,
    Unit,
    UnitInterval,
    UnitInputs,
    UnitEmpty,
    UnitOutput,
    UnitCoverage,
    UnitArtifact,
    ShuffleSourceCoverage,
    ShuffleRunNode,
    ResultChunk,
    Result,
    ResultVoteSubject,
    QuorumEvidence,
    VoteAccountability,
    LysisTerminal,
    ValidatorIdentity,
    KeyPop,
    SignOnceSlot,
    ActivationCall,
    LysisArithmetic,
    ResultEvidence,
    TerminalReceipt,
    NodReceipt,
    ContributorReceipt,
    TributeReceipt,
    DesisRequestBrief,
    BudgetSplitReceipt,
    CarryOverReceipt,
    ActiveGeneration,
    JobRecord,
    StateEvents,
    ApplyEventSummary,
    Effects,
    ListEmpty,
    ListLeaf,
    ListPad,
    ListNode,
    ListRoot,
}

impl HashDomain {
    pub const ALL: &'static [Self] = &[
        Self::ProtocolBundle,
        Self::PreAdmission,
        Self::ActivationPreconditions,
        Self::Intent,
        Self::IntentSlot,
        Self::Job,
        Self::InputLease,
        Self::InputChunk,
        Self::InputManifest,
        Self::CodecDescriptor,
        Self::OpeningCodecRegistry,
        Self::Plan,
        Self::Unit,
        Self::UnitInterval,
        Self::UnitInputs,
        Self::UnitEmpty,
        Self::UnitOutput,
        Self::UnitCoverage,
        Self::UnitArtifact,
        Self::ShuffleSourceCoverage,
        Self::ShuffleRunNode,
        Self::ResultChunk,
        Self::Result,
        Self::ResultVoteSubject,
        Self::QuorumEvidence,
        Self::VoteAccountability,
        Self::LysisTerminal,
        Self::ValidatorIdentity,
        Self::KeyPop,
        Self::SignOnceSlot,
        Self::ActivationCall,
        Self::LysisArithmetic,
        Self::ResultEvidence,
        Self::TerminalReceipt,
        Self::NodReceipt,
        Self::ContributorReceipt,
        Self::TributeReceipt,
        Self::DesisRequestBrief,
        Self::BudgetSplitReceipt,
        Self::CarryOverReceipt,
        Self::ActiveGeneration,
        Self::JobRecord,
        Self::StateEvents,
        Self::ApplyEventSummary,
        Self::Effects,
        Self::ListEmpty,
        Self::ListLeaf,
        Self::ListPad,
        Self::ListNode,
        Self::ListRoot,
    ];

    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProtocolBundle => "OUTBE_OCOMP_PROTOCOL_BUNDLE_V1",
            Self::PreAdmission => "OUTBE_OCOMP_PRE_ADMISSION_V1",
            Self::ActivationPreconditions => "OUTBE_OCOMP_ACTIVATION_PRECONDITIONS_V1",
            Self::Intent => "OUTBE_OCOMP_INTENT_V1",
            Self::IntentSlot => "OUTBE_OCOMP_INTENT_SLOT_V1",
            Self::Job => "OUTBE_OCOMP_JOB_V1",
            Self::InputLease => "OUTBE_OCOMP_INPUT_LEASE_V1",
            Self::InputChunk => "OUTBE_OCOMP_INPUT_CHUNK_V1",
            Self::InputManifest => "OUTBE_OCOMP_INPUT_MANIFEST_V1",
            Self::CodecDescriptor => "OUTBE_OCOMP_CODEC_DESCRIPTOR_V1",
            Self::OpeningCodecRegistry => "OUTBE_OCOMP_OPENING_CODEC_REGISTRY_V1",
            Self::Plan => "OUTBE_OCOMP_PLAN_V1",
            Self::Unit => "OUTBE_OCOMP_UNIT_V1",
            Self::UnitInterval => "OUTBE_OCOMP_UNIT_INTERVAL_V1",
            Self::UnitInputs => "OUTBE_OCOMP_UNIT_INPUTS_V1",
            Self::UnitEmpty => "OUTBE_OCOMP_UNIT_EMPTY_V1",
            Self::UnitOutput => "OUTBE_OCOMP_UNIT_OUTPUT_V1",
            Self::UnitCoverage => "OUTBE_OCOMP_UNIT_COVERAGE_V1",
            Self::UnitArtifact => "OUTBE_OCOMP_UNIT_ARTIFACT_V1",
            Self::ShuffleSourceCoverage => "OUTBE_OCOMP_SHUFFLE_SOURCE_COVERAGE_V1",
            Self::ShuffleRunNode => "OUTBE_OCOMP_SHUFFLE_RUN_NODE_V1",
            Self::ResultChunk => "OUTBE_OCOMP_RESULT_CHUNK_V1",
            Self::Result => "OUTBE_OCOMP_RESULT_V1",
            Self::ResultVoteSubject => "OUTBE_OCOMP_RESULT_VOTE_SUBJECT_V1",
            Self::QuorumEvidence => "OUTBE_OCOMP_QUORUM_EVIDENCE_V1",
            Self::VoteAccountability => "OUTBE_OCOMP_VOTE_ACCOUNTABILITY_V1",
            Self::LysisTerminal => "OUTBE_OCOMP_LYSIS_TERMINAL_V1",
            Self::ValidatorIdentity => "OUTBE_OCOMP_VALIDATOR_IDENTITY_V1",
            Self::KeyPop => "OUTBE_OCOMP_KEY_POP_V1",
            Self::SignOnceSlot => "OUTBE_OCOMP_SIGN_ONCE_SLOT_V1",
            Self::ActivationCall => "OUTBE_OCOMP_ACTIVATION_CALL_V1",
            Self::LysisArithmetic => "OUTBE_OCOMP_LYSIS_ARITHMETIC_V1",
            Self::ResultEvidence => "OUTBE_OCOMP_RESULT_EVIDENCE_V1",
            Self::TerminalReceipt => "OUTBE_OCOMP_TERMINAL_RECEIPT_V1",
            Self::NodReceipt => "OUTBE_OCOMP_NOD_RECEIPT_V1",
            Self::ContributorReceipt => "OUTBE_OCOMP_CONTRIBUTOR_RECEIPT_V1",
            Self::TributeReceipt => "OUTBE_OCOMP_TRIBUTE_RECEIPT_V1",
            Self::DesisRequestBrief => "OUTBE_OCOMP_DESIS_REQUEST_BRIEF_V1",
            Self::BudgetSplitReceipt => "OUTBE_OCOMP_BUDGET_SPLIT_RECEIPT_V1",
            Self::CarryOverReceipt => "OUTBE_OCOMP_CARRY_OVER_RECEIPT_V1",
            Self::ActiveGeneration => "OUTBE_OCOMP_ACTIVE_GENERATION_V1",
            Self::JobRecord => "OUTBE_OCOMP_JOB_RECORD_V1",
            Self::StateEvents => "OUTBE_OCOMP_STATE_EVENTS_V1",
            Self::ApplyEventSummary => "OUTBE_OCOMP_APPLY_EVENT_SUMMARY_V1",
            Self::Effects => "OUTBE_OCOMP_EFFECTS_V1",
            Self::ListEmpty => "OUTBE_OCOMP_LIST_EMPTY_V1",
            Self::ListLeaf => "OUTBE_OCOMP_LIST_LEAF_V1",
            Self::ListPad => "OUTBE_OCOMP_LIST_PAD_V1",
            Self::ListNode => "OUTBE_OCOMP_LIST_NODE_V1",
            Self::ListRoot => "OUTBE_OCOMP_LIST_ROOT_V1",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum ListKind {
    NodActions = 1,
    BucketRecords = 2,
    ContributorActions = 3,
    CompleteOutputManifest = 4,
    SemanticEventRecords = 5,
    InputChunkReferences = 6,
    UnitSpecificationsArtifacts = 7,
    RawTributeCoverage = 8,
    FidelityOpenings = 9,
    OracleOpenings = 10,
    ResultChunkHashes = 11,
    LysisLeagueFractions = 12,
    LysisGratisLeafPrefixes = 13,
}

impl ListKind {
    pub const ALL: &'static [Self] = &[
        Self::NodActions,
        Self::BucketRecords,
        Self::ContributorActions,
        Self::CompleteOutputManifest,
        Self::SemanticEventRecords,
        Self::InputChunkReferences,
        Self::UnitSpecificationsArtifacts,
        Self::RawTributeCoverage,
        Self::FidelityOpenings,
        Self::OracleOpenings,
        Self::ResultChunkHashes,
        Self::LysisLeagueFractions,
        Self::LysisGratisLeafPrefixes,
    ];

    #[must_use]
    pub const fn id(self) -> u16 {
        self as u16
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::NodActions => "Nod actions",
            Self::BucketRecords => "bucket records",
            Self::ContributorActions => "contributor actions",
            Self::CompleteOutputManifest => "complete output manifest",
            Self::SemanticEventRecords => "semantic event records",
            Self::InputChunkReferences => "input chunk references",
            Self::UnitSpecificationsArtifacts => "unit specifications/artifacts",
            Self::RawTributeCoverage => "raw Tribute coverage (raw_ordinal, tribute_id)",
            Self::FidelityOpenings => "Fidelity authenticated openings",
            Self::OracleOpenings => "Oracle authenticated openings",
            Self::ResultChunkHashes => "result-chunk hashes",
            Self::LysisLeagueFractions => "Lysis league fractions",
            Self::LysisGratisLeafPrefixes => "Lysis Gratis leaf prefixes",
        }
    }
}

impl TryFrom<u16> for ListKind {
    type Error = crate::error::ProtocolError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::NodActions),
            2 => Ok(Self::BucketRecords),
            3 => Ok(Self::ContributorActions),
            4 => Ok(Self::CompleteOutputManifest),
            5 => Ok(Self::SemanticEventRecords),
            6 => Ok(Self::InputChunkReferences),
            7 => Ok(Self::UnitSpecificationsArtifacts),
            8 => Ok(Self::RawTributeCoverage),
            9 => Ok(Self::FidelityOpenings),
            10 => Ok(Self::OracleOpenings),
            11 => Ok(Self::ResultChunkHashes),
            12 => Ok(Self::LysisLeagueFractions),
            13 => Ok(Self::LysisGratisLeafPrefixes),
            value => Err(crate::error::ProtocolError::UnknownListKind(value)),
        }
    }
}

pub const TRIBUTE_BODY_CODEC_DESCRIPTOR: &str = "role=TRIBUTE_BODY;version=1;wire=canonical-protobuf-payload-only;fields=1:bytes36-tribute_id-required,2:bytes20-owner-required,3:uint32-worldwide_day-omit-zero,4:bytes32-issuance_amount_minor-required-big-endian,5:uint16-issuance_currency-omit-zero,6:bytes32-nominal_amount_minor-required-big-endian,7:uint16-reference_currency-omit-zero,8:bytes32-tribute_price_minor-required-big-endian,9:bool-exclude_from_intex_issuance-omit-false;rules=ascending-unique-fields,minimal-varints,no-unknown-fields,strict-decode-reencode,identity-day-match;commitment=CE_BODY_COMMITMENT_V1(schema_version=1,payload);stored_body_envelope=excluded";
pub const TRIBUTE_BODY_CODEC_ID: alloy_primitives::B256 = alloy_primitives::B256::new([82, 227, 209, 195, 86, 32, 174, 112, 204, 29, 168, 232, 64, 52, 140, 96, 196, 181, 137, 113, 150, 11, 173, 234, 112, 74, 55, 254, 51, 64, 255, 202]);

pub const FIDELITY_OPENING_CODEC_DESCRIPTOR: &str = "role=FIDELITY_OPENING;version=1;record=AuthenticatedOpeningV1(source_kind=1,subject,value,codec_id,opening);subject=u32_be(owner_count)||address20*;owner_count=1..256;owners=strict-ascending-unique;value=u32_be(slot_count)||(slot:B256||value:U256_be)*;slots=fidelity_slot_plan_v1(qualified_start_base=0,active_count_base=1,active_cohorts_base=2,sold_count_base=4,sold_cohorts_base=5,first_qualified_start=8,mapping=keccak256(key||slot32),active_count<=64,sold_count<=64);opening=address20||state_root:B256||u32_be(slot_count)||(slot:B256||value:U256_be)*||u32_be(account_proof_len)||account_proof||u32_be(storage_proof_len)||storage_proof;proof=RETH_ETHEREUM_ACCOUNT_STORAGE_MPT_V1;rules=state_root_equals_checkpoint,exact-contract,exact-slot-plan,strict-decode-reencode";
pub const FIDELITY_OPENING_CODEC_ID: alloy_primitives::B256 = alloy_primitives::B256::new([61, 58, 197, 129, 143, 184, 46, 81, 195, 4, 30, 36, 233, 255, 54, 204, 95, 220, 232, 219, 219, 116, 218, 31, 191, 57, 120, 255, 14, 25, 222, 26]);

pub const ORACLE_OPENING_CODEC_DESCRIPTOR: &str = "role=ORACLE_OPENING;version=1;record=AuthenticatedOpeningV1(source_kind=2,subject,value,codec_id,opening);subject=u32_be(wwd)||u16_be(iso_count)||u16_be(iso)*;isos=strict-ascending-unique-and-contains-840-and-subset-of-reference-currencies;value=u32_be(slot_count)||(slot:B256||value:U256_be)*;slots=oracle_slot_plan_v1(pair_index=10,scurve_count=34,scurve_pair=35,scurve_peak_day=36,scurve_peak_price=37,scurve_oldest=38,wwd_vwap_exists=47,wwd_vwap_pair_count=50,wwd_vwap_pair=51,wwd_vwap_value=52,reference_currencies=55,mapping=keccak256(key||slot32),vec=keccak256(slot32)+index,pair_key=sorted_concat(address20(coen=0x00*20),address20(iso=0x000cc||bcd3(iso))),pair_value=address20(base)@slot||address20(quote)@slot+1,wwd_pairs<=256,active_scurve<=256,reference_currencies<=256,isos<=256);opening=address20||state_root:B256||u32_be(slot_count)||(slot:B256||value:U256_be)*||u32_be(account_proof_len)||account_proof||u32_be(storage_proof_len)||storage_proof;proof=RETH_ETHEREUM_ACCOUNT_STORAGE_MPT_V1;rules=state_root_equals_checkpoint,exact-contract,exact-slot-plan,strict-decode-reencode";
pub const ORACLE_OPENING_CODEC_ID: alloy_primitives::B256 = alloy_primitives::B256::new([66, 239, 224, 201, 72, 42, 112, 165, 100, 211, 70, 148, 50, 133, 181, 245, 72, 234, 33, 100, 69, 10, 159, 118, 93, 219, 114, 224, 46, 189, 169, 209]);

pub const OPENING_CODEC_REGISTRY_HASH: alloy_primitives::B256 = alloy_primitives::B256::new([147, 21, 214, 144, 198, 222, 62, 99, 102, 34, 220, 199, 17, 28, 181, 118, 110, 54, 185, 177, 77, 87, 168, 111, 15, 209, 30, 55, 78, 81, 84, 169]);
