// Extract ABIs from the Forge build output (out/) to the abi-export directory.
// Used during package publishing to create clean ABI exports. Run after `forge build`.

import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "out";
const DIST_DIR = "dist";
const OUTPUT_DIR = "abi-export";

// Contracts to extract ABIs for
const CONTRACTS = [
  // Target-side
  "target/IntexAuction",
  "target/EscrowAdapter",
  "target/TargetRouter",
  // Origin-side (precompile interfaces live in contracts/precompiles, not here)
  "origin/OriginRouter",
  // Both chains
  "shared/IntexNFT1155",
  "shared/IntexNFT1155Bridge",
];

const INTERFACES = [
  // Target-side
  "target/interfaces/IIntexAuction",
  "target/interfaces/IEscrowAdapter",
  "target/interfaces/ITargetRouter",
  // Origin-side (precompile interfaces live in contracts/precompiles, not here)
  "origin/interfaces/IOriginRouter",
  // Both chains
  "shared/interfaces/IIntexNFT1155",
  "shared/interfaces/IIntexNFT1155Bridge",
];

interface ArtifactJson {
  abi: unknown[];
}

function extractAbi(contractPath: string): void {
  // Forge keys its build output by source-file basename: out/<Name>.sol/<Name>.json.
  const contractName = contractPath.split("/").pop() as string;
  const artifactPath = path.join(OUT_DIR, `${contractName}.sol`, `${contractName}.json`);

  if (!fs.existsSync(artifactPath)) {
    console.warn(`Warning: Artifact not found for ${contractPath} at ${artifactPath}`);
    return;
  }

  const artifact: ArtifactJson = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));

  if (!artifact.abi || artifact.abi.length === 0) {
    console.warn(`Warning: Empty ABI for ${contractPath}`);
    return;
  }

  const outputPath = path.join(OUTPUT_DIR, `${contractName}.json`);

  // Clean export: just the contract name + ABI.
  const output = {
    contractName,
    abi: artifact.abi,
  };

  fs.writeFileSync(outputPath, JSON.stringify(output, null, 2));
  console.log(`[OK] Extracted ABI: ${contractName} (${artifact.abi.length} entries)`);
}

function main(): void {
  console.log("Extracting ABIs from artifacts...\n");

  // Ensure output directory exists
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  // Extract contract ABIs
  console.log("Contracts:");
  for (const contract of CONTRACTS) {
    extractAbi(contract);
  }

  // Extract interface ABIs
  console.log("\nInterfaces:");
  for (const iface of INTERFACES) {
    extractAbi(iface);
  }

  // Create an index file in dist/abi/ for direct ABI subpath imports
  const abiIndexContent = [
    "// Auto-generated ABI exports",
    "",
    ...CONTRACTS.map((c) => {
      const name = c.split("/").pop();
      return `export { default as ${name}ABI } from './${name}.json';`;
    }),
    "",
    ...INTERFACES.map((i) => {
      const name = i.split("/").pop();
      return `export { default as ${name}ABI } from './${name}.json';`;
    }),
    "",
  ].join("\n");

  fs.writeFileSync(path.join(OUTPUT_DIR, "index.ts"), abiIndexContent);
  console.log("\n[OK] Created ABI index file");

  // Create the package entry points (dist/index.js + dist/index.d.ts).
  // Kept here so the export list stays in sync with CONTRACTS + INTERFACES.
  const allNames = [...CONTRACTS, ...INTERFACES].map(
    (c) => c.split("/").pop() as string
  );

  const indexJs = [
    "// Auto-generated by scripts/cd/extract-abi.ts - do not edit by hand.",
    ...allNames.map(
      (n) => `import ${n}ABI from '../abi-export/${n}.json' with { type: 'json' };`
    ),
    "",
    `export { ${allNames.map((n) => `${n}ABI`).join(", ")} };`,
    "",
    "export const loadAddresses = async (network) => {",
    "  const module = await import(`./addresses/${network}.json`, { with: { type: 'json' } });",
    "  return module.default;",
    "};",
    "",
  ].join("\n");

  const indexDts = [
    "// Auto-generated by scripts/cd/extract-abi.ts - do not edit by hand.",
    ...allNames.map(
      (n) =>
        `export declare const ${n}ABI: { contractName: string; abi: unknown[] };`
    ),
    "export declare const loadAddresses: (network: string) => Promise<{",
    "  contracts: Record<string, string>;",
    "  tokens: Record<string, string>;",
    "  external: Record<string, string>;",
    "}>;",
    "",
  ].join("\n");

  fs.mkdirSync(DIST_DIR, { recursive: true });
  fs.writeFileSync(path.join(DIST_DIR, "index.js"), indexJs);
  fs.writeFileSync(path.join(DIST_DIR, "index.d.ts"), indexDts);
  console.log(`[OK] Created package index with ${allNames.length} ABI exports`);

  console.log("\nABI extraction complete!");
}

main();
