[package]
name = "outbe-stablecoinfactory"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
outbe-macros.workspace = true
outbe-primitives = { workspace = true, features = ["test-utils"] }
outbe-stablecoin.workspace = true
outbe-stablecoinpolicy.workspace = true
revm.workspace = true
thiserror.workspace = true

[lints]
workspace = true
