[package]
name = "outbe-node"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
# Internal
outbe-evm.workspace = true
outbe-compressed-entities.workspace = true
outbe-primitives.workspace = true
outbe-txpool.workspace = true
outbe-offchain-data.workspace = true
outbe-offchain-storage.workspace = true
outbe-consensus.workspace = true
outbe-metadosis.workspace = true
outbe-ocomp-protocol.workspace = true
outbe-oracle.workspace = true
outbe-tribute.workspace = true
outbe-tee.workspace = true
outbe-teeregistry.workspace = true
outbe-validatorset.workspace = true

# Reth
reth-ethereum = { workspace = true, features = ["node", "cli", "exex"] }
reth-chainspec.workspace = true
reth-basic-payload-builder.workspace = true
reth-consensus-common.workspace = true
reth-node-builder.workspace = true
reth-ethereum-payload-builder.workspace = true
reth-db.workspace = true
reth-errors.workspace = true
reth-execution-types.workspace = true
reth-evm.workspace = true
reth-provider.workspace = true
reth-engine-primitives.workspace = true
reth-payload-builder.workspace = true
reth-payload-builder-primitives.workspace = true
reth-payload-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-revm.workspace = true
reth-storage-api.workspace = true
reth-transaction-pool.workspace = true
reth-trie.workspace = true
reth-tasks.workspace = true
revm.workspace = true

# Utilities
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-sol-types.workspace = true
either.workspace = true
eyre.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
futures.workspace = true
metrics.workspace = true
x25519-dalek.workspace = true
serde.workspace = true
thiserror.workspace = true
k256.workspace = true

[dev-dependencies]
reth-engine-tree = { git = "https://github.com/paradigmxyz/reth.git", tag = "v2.2.0" }
reth-stages-api = { git = "https://github.com/paradigmxyz/reth.git", tag = "v2.2.0" }
reth-static-file = { git = "https://github.com/paradigmxyz/reth.git", tag = "v2.2.0" }
outbe-chain-constants.workspace = true
outbe-primitives = { workspace = true, features = ["test-utils"] }
outbe-metadosis = { workspace = true, features = ["test-utils"] }
outbe-tee-enclave = { workspace = true, features = ["mock"] }
alloy-provider.workspace = true
alloy-trie.workspace = true
ed25519-dalek.workspace = true
mongodb.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
reth-e2e-test-utils.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-rpc-server-types.workspace = true
reth-tracing.workspace = true
serde_json.workspace = true
hex.workspace = true
tempfile.workspace = true

[lints]
workspace = true
