[package]
name = "outbe-chain-constants"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
test-protocol-overrides = []

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
