[package]
name = "outbe-offchain-data"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["serde", "std"] }
alloy-sol-types = { workspace = true, features = ["std"] }
outbe-compressed-entities.workspace = true
outbe-nod.workspace = true
outbe-offchain-storage.workspace = true
outbe-primitives.workspace = true
outbe-tribute.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "sync"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
